#!/usr/bin/env bash

# ----------------------------------------------------
# Setup CRON script (execute every 5 minutes):
# ----------------------------------------------------
# $ crontab -e
# */5 * * * * /path/to/bash/script/battery_status
# ----------------------------------------------------

# Get information via ACPI
BATTINFO=`acpi -b`

# Check if battery is low
if [[ `echo $BATTINFO | grep Discharging` && `echo $BATTINFO | cut -f 5 -d " "` < 00:30:00 ]] ; then
    # DISPLAY=:0.0 /usr/bin/notify-send "low battery" "$BATTINFO"
    DISPLAY=:0.0 /usr/bin/notify-send -u critical "WARNING" "Low Battery"
fi

# Check if battery is fully charged (100%)
if [[ `echo $BATTINFO | grep Charging` && `echo $BATTINFO | cut -f 4 -d " "` == "100%," ]] ; then
    DISPLAY=:0.0 /usr/bin/notify-send -u normal "INFORMATION" "Battery Fully Charged"
fi
